sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
env:
  - DB=postgres ORM=active_record RAILS_VERSION=4.2
  - DB=mysql ORM=active_record RAILS_VERSION=4.2
  - DB=sqlite3 ORM=active_record RAILS_VERSION=4.2
  - DB=postgres ORM=active_record RAILS_VERSION=5.0
  - DB=mysql ORM=active_record RAILS_VERSION=5.0
  - DB=sqlite3 ORM=active_record RAILS_VERSION=5.0
  - DB=postgres ORM=active_record RAILS_VERSION=5.1
  - DB=mysql ORM=active_record RAILS_VERSION=5.1
  - DB=sqlite3 ORM=active_record RAILS_VERSION=5.1
  - DB=postgres ORM=active_record RAILS_VERSION=5.2
  - DB=mysql ORM=active_record RAILS_VERSION=5.2
  - DB=sqlite3 ORM=active_record RAILS_VERSION=5.2
  - DB=postgres ORM=active_record RAILS_VERSION=latest
  - DB=mysql ORM=active_record RAILS_VERSION=latest
  - DB=sqlite3 ORM=active_record RAILS_VERSION=latest
  - DB=postgres ORM=sequel SEQUEL_VERSION=4
  - DB=mysql ORM=sequel SEQUEL_VERSION=4
  - DB=sqlite3 ORM=sequel SEQUEL_VERSION=4
  - DB=postgres ORM=sequel SEQUEL_VERSION=5
  - DB=mysql ORM=sequel SEQUEL_VERSION=5
  - DB=sqlite3 ORM=sequel SEQUEL_VERSION=5
  - DB=sqlite3 ORM= TEST_PERFORMANCE=true
  - DB=sqlite3 ORM= I18N_FALLBACKS=true
matrix:
  fast_finish: true
before_script:
  - bundle exec rake db:create db:up
before_install: gem install bundler
addons:
  postgresql: "9.4"
  apt:
    update: true
services:
  - postgresql
  - mysql
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/952962a1b06353b27efa
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
