sudo: false
language: ruby
rvm:
  - 2.2.5
  - 2.3.1
env:
  matrix:
    - DB=postgres ORM=active_record
    - DB=mysql    ORM=active_record
    - DB=sqlite3  ORM=active_record
    - DB=postgres ORM=sequel
    - DB=mysql    ORM=sequel
    - DB=sqlite3  ORM=sequel
    - DB=sqlite3  ORM=
before_script:
  - bundle exec rake db:create db:up
before_install: gem install bundler -v 1.12.5
addons:
  postgresql: "9.4"
services:
  - postgresql
